{
 "title": "Pizza Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Grafaga logging",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "{service_name=\"jwt-pizza-service\"} |= `` | json"
    }
   ]
  },
  {
   "title": "Pizza purchases",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "Pizza_purchases_sold{source=\"jwt-pizza-service\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "Pizza_purchases_purchase_failure{source=\"jwt-pizza-service-dev\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "http_requests_total{source=\"jwt-pizza-service\", method=\"all\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "http_requests_total{source=\"jwt-pizza-service\", method=\"delete\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "http_requests_total{source=\"jwt-pizza-service\", method=\"get\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "http_requests_total{source=\"jwt-pizza-service\", method=\"post\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "http_requests_total{source=\"jwt-pizza-service\", method=\"put\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU & Memory",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_cpu_usage{source=\"jwt-pizza-service\"}",
     "legendFormat": "{{label_name}}"
    },
    {
     "expr": "system_memory_usage{source=\"jwt-pizza-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "Request_Latency_ms{source=\"jwt-pizza-service\"}",
     "legendFormat": "{{Request Latency}}"
    }
   ]
  },
  {
   "title": "Authentications",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "auth_attempts_per_minute_success{source=\"jwt-pizza-service\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "auth_attempts_per_minute_failure{source=\"jwt-pizza-service-dev\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Revenue",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "currencyBTC" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Revenue_revenue{source=\"jwt-pizza-service\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}